services:
  mysql:
    image: mysql:8.0
    container_name: garage-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: garage
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - garage-mysql-data:/var/lib/mysql

volumes:
  garage-mysql-data: